name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install

    - name: Deploy to Server
      run: |
        # Adicione aqui os comandos necessários para fazer o deploy no servidor
        # Por exemplo:
        # Copiar arquivos, reiniciar serviços, etc.
        # Exemplo:
        # cp -r * /path/to/your/application
        # systemctl restart your-service


